#ifndef GETCHANNELACTIONSRESPONSEJSON_H
#define GETCHANNELACTIONSRESPONSEJSON_H

#include "DefaultResponseJSON.h"

typedef DefaultResponseJSON GetChannelActionsResponseJSON;

#endif // GETCHANNELACTIONSRESPONSEJSON_H
