#!/bin/bash

#time ./testForsession

curl -d "{\"login\":\"Kirill\",\"password\":\"test\"}"  http://localhost:80/service?query=login > loginResult
cut -d'"' -f4 loginResult > loginResult2

a=`cat loginResult2`

curl -d "{\"auth_token\":\"$a\",\"latitude\" : 60, \"longitude\" : 30, \"time\" : \"01 09 2010 09:00:47.630\", \"timeSlot\":86400, \"radius\":10, \"isCurrentTime\":1}"  http://localhost:80/service?query=setSessionPoint


for((i=0; i<500; ++i))
do 
	curl -d "{\"auth_token\":\"$a\"}"  http://localhost:80/service?query=rssSession
done 


